export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER ";
export const GET_USER_NOTES = "GET_USER_NOTES";
export const CLEAR_NOTES = "CLEAR_NOTES";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
